# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'

  # Root
  - package-ecosystem: 'npm' #
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      jest:
        patterns:
          - '@types/jest'
          - 'jest'
      nestjs:
        patterns:
          - '@nestjs/common'
          - '@nestjs/testing'
      prettier:
        patterns:
          - 'eslint-config-prettier'
          - 'eslint-plugin-prettier'
          - 'prettier'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'

  # Cacheable
  - package-ecosystem: 'npm'
    directory: 'packages/cacheable'
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Google Maps
  - package-ecosystem: 'npm'
    directory: 'packages/google-maps'
    schedule:
      interval: 'monthly'
    assignees:
      - 'emackie-eddaic'
    reviewers:
      - 'emackie-eddaic'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
